### ISSUE TITLE
Not saving

### ISSUE THREAD

**Issue by net4u** [AnkitSharma-007/ExpenseManager-ASPCore-EFCore-Highchart#1]
Hi,

I noticed that the app is not saving in Db without firing any error.

**Comment by net4u** [comment]
I found that is related to Date validation
[DisplayFormat(DataFormatString = "{0:MM.dd.yyyy}", ApplyFormatInEditMode = true)]

**Comment by AnkitSharma-007** [comment]
The date format should match the date format of your machine.
